homeassistant:
  name: Maison
  latitude: 36.8
  longitude: 10.2
  elevation: 10
  unit_system: metric
  time_zone: Europe/Tunis

mqtt:
  broker: mosquitto
  port: 1883

camera:
  - platform: generic
    name: exemple_cam
    still_image_url: http://localhost:5000/still/image/exemple_cam/latest.jpg
    stream_source: http://localhost:5000/live/exemple_cam

