mqtt:
  enabled: false

cameras:
  exemple_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:L282777A@10.0.22.50:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1         # Garde les clips pendant 1 jour
        mode: motion    # Enregistre seulement lors des détections de mouvement
version: 0.15-1
