
mqtt:
  enabled: true
  host: mosquitto   # nom du service Docker
  port: 1883
detect:
  enabled: true

version: 0.16-0

cameras:
  exemple_cam:
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:L282777A@10.0.22.50:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - record
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
        mode: motion


#face:
  #enabled: true
  #model:
    #path: /config/models/face_recognition.onnx   # chemin vers ton modèle ONNX
  #known_faces:
    #chayma:
      #path: /media/faces/chayma.webp
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    objects:
      filters:
        person:
          mask: 0.702,0.7,1,0.365,1,1
    notifications:
      enabled: false
semantic_search:
  enabled: true
  model_size: small
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
notifications:
  enabled: false
  email: chayma.hamdi@ensi-uma.tn
